title: 'Swift Korea Meetup'
description: 'Swift Korea 커뮤니티에서 주최하는 개발자 행사입니다.'
logo: '/images/logo.svg'
logo_image: '/images/logo-image.png'
baseurl: '/meetup'
url: 'https://swiftkorea.github.io/meetup/'
onoffmix: 'http://onoffmix.com/event/96420'
exclude:
  - scripts
  - venv
  - vendor
collections:
  - sections
